server_url: 
  - https://proxypool.xiaonuo.live

# For your local server
request: http   # http / https
domain:         # default: 127.0.0.1
port: 12586     # default: 80

cron_interval: 15       # default: 15  minutes
show_remote_speed: true # default false

healthcheck_timeout:    # default 5
healthcheck_connection: # default 100

speedtest:              # default false
speed_connection:       # default 5
speed_timeout:          # default 10
